config/routes.rb
Rails.application.routes.draw do
  resources :todos do
    collection do
      delete :clear_completed
      post :toggle_all
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
scope :active, -> { where(completed: false) }
scope :completed, -> { where(completed: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @scope = params[:scope] || "all"
    @todos = Todo.all
    @todos = case @scope
    when "active"
        @todos.active
    when "completed"
        @todos.completed
    else
        @todos
    end

    @todo = Todo.new
    @todosLeftCount = Todo.active.count
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to action: :index }

      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        # sleep 3
        format.html { redirect_to action: :index }
      else
        format.html { render :edit, status: :unprocessable_entity }

      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy!

    respond_to do |format|
      format.html { redirect_to todos_path, status: :see_other, notice: "Todo was successfully destroyed." }
    end
  end

  def clear_completed
    Todo.completed.destroy_all

    respond_to do |format|
      format.html { redirect_to todos_path, status: :see_other, notice: "Completed todos were successfully destroyed" }
    end
  end

  def toggle_all
    check_all = params[:check_all]
    Todo.update_all(completed: check_all)
    @todos = Todo.all

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(:list, partial: "list")
      end
      format.html { redirect_to todos_path, status: :see_other, notice: "All todos were successfully toggled" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.expect(todo: [ :title, :completed ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Todo Rails8" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <footer class="info">
            <p>Double-click to edit a todo</p>
			<p>Created by the TodoMVC Team</p>
			<p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
        </footer>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <%= form.text_field :title, class: "new-todo", placeholder: "What needs to be done?", autofocus: true, data: {"turbo-frame": "_top"} %>
<% end %>

app/views/todos/_list.html.erb
<div id="list">
  <main class="main">
    <div class="toggle-all-container">
      <%=check_box_tag "toggle-all", checked: @todos.all?(&:completed?), class: "toggle-all", data: {controller: "toggle-all", action: "click->toggle-all#toggleAll", "toggle-all-url-value": toggle_all_todos_path}  %>
      <label class="toggle-all-label" for="toggle-all">Mark all as complete</label>
    </div>
    <ul class="todo-list">
      <%=render @todos%>
    </ul>
  </main>
  <footer class="footer">
    <span class="todo-count"><%=pluralize @todosLeftCount, "item left", "items left"%></span>
    <ul class="filters">
      <li>
        <a href="<%=todos_path%>" class="<%=class_names "selected": @scope == "all" || @scope.nil?%>">All</a>
      </li>
      <li>
        <a href="<%=todos_path(scope: "active")%>" class="<%=class_names "selected": @scope == "active"%>">Active</a>
      </li>
      <li>
        <a href="<%=todos_path(scope: "completed")%>" class="<%=class_names "selected": @scope == "completed"%>">Completed</a>
      </li>
    </ul>
    <%= button_to "Clear completed", clear_completed_todos_path, method: :delete, data: { "turbo-frame": "_top" }, class: "clear-completed" %>
  </footer>
</div>

app/views/todos/_todo.html.erb
<li class="<%= class_names(completed: todo.completed?) %>">
  <turbo-frame id="<%= dom_id todo, :edit %>">
    <%= form_with(model: todo,  data: { controller: "form-toggle", "turbo-frame": "_top" }) do |form| %>
      <%=tag.div class: "view", data: {controller: "inline-edit", action: "dblclick->inline-edit#render", "inline-edit-url-value": edit_todo_path(todo)} do %>
        <%= form.checkbox :completed, class: "toggle", data: { action: "form-toggle#submit" } %>
        <label><%=todo.title%></label>
      <%end%>
    <% end %>
    <%= button_to "", todo_path(todo), method: :delete, data: { "turbo-frame": "_top" }, class: "destroy" %>
  </turbo-frame>
</li>

app/views/todos/edit.html.erb
<% content_for :title, "Editing todo" %>
<h1>Editing todo</h1>
<%= turbo_frame_tag  dom_id(@todo, :edit) do %>
  <%= render "form", todo: @todo %>
  <span class="loader"></span>
<% end %>

app/views/todos/index.html.erb
<p style="color: green"><%= notice %></p>
<% content_for :title, "Todos" %>
<section class="todoapp">
  <header class="header">
    <h1>todos</h1>
    <%= render "form", todo: @todo%>
  </header>
  <% if @todos.present? %>
    <%= render partial: "list"%>
  <% end %>
</section>

app/views/todos/new.html.erb
<% content_for :title, "New todo" %>

<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>